### ISSUE TITLE
Site requirements cannot be satisfied.

### ISSUE THREAD

**Issue by usherbob** [hartikainen/stanford-cs231n#1]
When I tried to install the requirement for virtual environment in assignment 1, I could not install site 0.0.1 version. There is a error reporting that`Could not find a version that satisfies the requirement site==0.0.1 (from -r requirements.txt (line 42)) (from versions: ). No matching distribution found for site==0.0.1 (from -r requirements.txt (line 42))`. I do not know what happened, really hoping that someone could help me out.

**Comment by hartikainen** [comment]
I went ahead an remove the `site==0.0.1` from requirements.txt, and it should work now. I haven't tested actually running the code with the latest commit, but pip installation goes through without problems.

**Comment by usherbob** [comment]
Yes, Thanks for your reply, it did go through after commenting `site==0.0.1`. I am just not sure whether it causes problems as the framework of assignment 1 could not run on my ubuntu.

**Comment by usherbob** [comment]
Yes, Thanks for your reply, pip install goes through after commenting `site==0.0.1`. However, I am not sure whether it causes problems as the framework of assignment 1 could not run on my ubuntu.

**Comment by frogcjn** [comment]
Same issue. If changed to sites==0.0.1, more problems would appear.

**Comment by hartikainen** [comment]
Sorry guys, I would love to help but  I don't currently have access to ubuntu environment. I believe everything should work on osx. `sites` package is actually not a top level dependency but is only a sub-dependency for some other package. What you could do is try removing the failing lines from requirements and reinstall packages (something like `pip install -r requirements.txt`).

**Comment by imLinkang** [comment]
I change it into "sites==0.0.1", and then more problems appear.
I fixed it by following: 
1) $ sudo apt-get install libncurses5-dev
2) $ pip install -r requirements.txt
and  there are no errors appear.

**Comment by yanivbenny** [comment]
For me after commenting out "site==0.0.1", there was an error with "Pillow==3.0.0"

My fix was:
- Comment both "site" and "Pillow"
- Install Pillow manually "pip install Pillow"
- run "pip install -r requirements.txt"

**Comment by Feiyu-Zhang** [comment]
You can use **conda install  Pillow=3.0.0**
